import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "DR. Monk",
  description: "Generated by create next app",
    icons: {
      icon: 'public/drmonklogo128x128.png'
    }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
